version = 0.1
[default.deploy.parameters]
stack_name = "riskapp-api"
resolve_s3 = true
s3_prefix = "riskapp-api"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
